services:
  app:
    build: .
    container_name: docfilter-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/opt/docfilter/backend/data
    restart: always
    user: "1000:1000" # Forza l'esecuzione con lo stesso UID/GID del primo utente Linux (es. Andrea)
